framework:
  secret: '%env(APP_SECRET)%'
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
  php_errors:
    log: true
  csrf_protection:
    # https://symfony.com/doc/5.3/reference/configuration/framework.html#enabled
    enabled: false
