services:
  # Default configuration for services in *this* file
  _defaults:
    autowire: true     # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # Makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']

  App\Doctrine\:
    resource: '../src/Doctrine/'
    tags: ['doctrine.orm.entity_listener']

  App\EventListener\:
    resource: '../src/EventListener/'
    tags: ['kernel.event_listener']

  App\EventListener\ResourceResolvingListener:
    class: 'App\EventListener\ResourceResolvingListener'
    tags:
      - {name: kernel.event_listener, priority: 1}
        
  App\Service\FileUploader:
    arguments:
      $targetDirectory: '%images_directory%'

parameters:
  images_directory: '%kernel.project_dir%/public/uploads/images'
